name: env-optionsbot
channels:
  - default
  - conda-forge
dependencies:
  # environment
  - python
  - pip
  # data handling
  - pandas
  # web service
  - fastapi
  # financial analysis
  - finta # Common financial technical indicators implemented in Pandas
  - pip:
    - uvicorn[standard]